FROM scratch AS stage0

ARG BOOTSH
COPY $BOOTSH /bin/sh

SHELL ["/bin/sh", "-c"]
CMD ["/bin/sh"]

COPY test/build /build
COPY test/tarballs /build
WORKDIR /build
RUN ./bootstrap.sh
RUN make -j$(nproc) gawk binutils bzip2 linux-headers

RUN mkdir /sabotage && cd /sabotage && mkdir -p \
        boot bin dev etc home lib mnt proc root share srv src sys tmp var \
        src/logs src/build src/tarballs src/pkg src/KEEP \
        var/log/sshd var/log/crond var/log/dmesg \
        var/empty var/service var/lib var/run var/spool/cron/crontabs && \
    ln -sfn . usr && ln -sfn bin sbin && ln -sfn ../tmp var/tmp && \
    chmod 775 src/build && chmod 1777 tmp && chmod 700 root

COPY test/sabotage/KEEP/etc/ /sabotage/etc/
COPY test/sabotage/KEEP/boot/ /sabotage/boot/
COPY test/sabotage/COOKBOOK.md test/sabotage/LICENSE test/sabotage/README.md test/sabotage/build-stage0 test/sabotage/enter-chroot /sabotage/src/
COPY test/sabotage/KEEP /sabotage/src/KEEP
COPY test/sabotage/pkg /sabotage/src/pkg
COPY test/sabotage/utils /sabotage/src/utils
COPY test/config.sabotage /tmp/config
COPY test/tarballs /sabotage/src/tarballs

RUN chmod 0600 /sabotage/etc/shadow && ln -s /proc/mounts /sabotage/etc/mtab && \
    sed -i "s@MAKE_THREADS=1@MAKE_THREADS=$(nproc)@" /tmp/config && \
    ln -sf /usr/local/bin/gawk /usr/local/bin/awk

WORKDIR /sabotage/src
RUN CONFIG=/tmp/config BUTCHDB=/sabotage/var/lib/butch.db DEPS=build:stage0 KEEP/bin/butch install stage0 && \
    echo "export A=$(uname -m)" > config && \
    cat /sabotage/src/KEEP/config.stage1 >> config && \
    sed -i "s@MAKE_THREADS=1@MAKE_THREADS=$(nproc)@" config


FROM scratch AS stage1

COPY test/sabotage-stage0 /

RUN strip --strip-unneeded /opt/stage0-musl/lib/*.a /opt/stage0-musl/lib/*.o /opt/stage0-musl/lib/*.so && \
    ranlib /opt/stage0-musl/lib/*.a

RUN butch install stage1           # Installs core system + build chain
RUN /src/utils/clean-stage1.sh     # remove unneeded bootstrap packages
RUN /src/utils/rebuild-stage1.sh   # rebuild core packages with the stage1 gcc
