FROM bootsh

WORKDIR /root
RUN ./boot.sh

COPY configure Makefile toybox.config config.h bootsh/
COPY src bootsh/src
COPY lib bootsh/lib
COPY test/cc bootsh/test/cc

RUN make sh && cp /bin/sh /bin/sh0
RUN make -C bootsh test-host

RUN make sh && cp /bin/sh /bin/sh1
RUN make -C bootsh test-host

RUN make sh && cp /bin/sh /bin/sh2
RUN make -C bootsh test-host

RUN diff -q /bin/sh1 /bin/sh2
