ARG BASE
FROM $BASE AS build

RUN --mount=type=cache,target=/src/tarballs /bin/boot.sh bash

WORKDIR /tmp
COPY configure Makefile bootsh/
COPY src bootsh/src
COPY lib bootsh/lib
RUN cd bootsh && ./configure && make clean && make


FROM scratch
COPY --from=build /tmp/bootsh/bootsh /bin/sh
COPY boot.sh /bin/boot.sh
COPY Makefile.packages /tmp/Makefile
COPY wak.c /bin/awk
ENTRYPOINT ["/bin/boot.sh"]
