name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: davidar
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: davidar/bootsh:latest
          platforms: linux/amd64,linux/i386
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Test
        run: make test-latest -o docker-latest
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: davidar/bootsh:latest
          platforms: linux/amd64,linux/i386
